print(True and True, "\t True")
print(False and True, "\t False")
print(1==1 and 2==1, "\t False")
print("test"=="test", "\t True")
print(1==1 or 2!=1, "\t True") #here
print(True and 1==1, "\t True")
print(False and 0 != 0, "\t False")
print(True or 1==1, "\t True")
print("test"=="testing", "\t False")
print(1!=0 and 2==1, "\t False")
print("test" != "testing", "\t True")
print("test"==1, "\t False")
print(not(True and False), "\t True")
print(not (1==1 and 0!=1), "\t False")
print(not(10==1 or 1000==1000), "\t False")
print(not (1!=10 or 3==4), "\t False")
print(not ("testing" == "testing" and "Zed" == "Cool Guy"), "\t True")
print(1==1 and (not ("Testing"==1 or 1==0)), "\t True")
print("chunky"=="bacon" and (not (3==4 or 3==3)), "\t False")
print(3==3 and (not("Testing"=="Testing" or "Python" == "Fun")), "\t False")